fixtures:
    symlinks:
      bacula: "#{source_dir}"
    forge_modules:
      'concat':       'puppetlabs/concat'
      'extlib':       'puppet/extlib'
      'firewall':     'puppetlabs/firewall'
      'mysql':        'puppetlabs/mysql'
      'postgresql':   'puppetlabs/postgresql'
      'sqlite':       'puppetlabs/sqlite'
    repositories:
      selinux:
        repo: https://github.com/blackknight36/puppet-selinux-1.git
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 5.2.0
